controllers/ArticleController.php
<?php
/**
 * Created by PhpStorm.
 * User: yurac
 * Date: 31.01.2019
 * Time: 16:15
 */

namespace app\controllers;


use app\models\article\Article;
use app\models\category\Category;
use app\models\comment\CommentForm;
use app\models\forms\ImageUpload;
use app\models\tag\Tag;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\UploadedFile;

class ArticleController extends Controller {
    public function actionUpdate($id) {
        var_dump($id);
        die;
    }

    public function actionGet($id) {

        $article = Article::findOne($id);

        $popular = Article::getPopular();

        $categories = Category::getAll();

        $comments = $article->comments;
        $commentForm = new CommentForm();

        $tags = Tag::getAll();
        $articleTags = $article->tags;

        return $this->render('single', [
            'article' => $article,
            'articleTags' => $articleTags,
            'popular' => $popular,
            'categories' => $categories,
            'tags' => $tags,
            'comments' => $comments,
            'commentForm' => $commentForm,
        ]);
    }

    public function actionComment($id) {
        $model = new CommentForm();

        if (Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            if ($model->saveComment($id)) {
                return $this->redirect(['/article/get', 'id' => $id]);
            }
        }
    }

    public function actionAddArticle() {
        $model = new Article();

        $categories = ArrayHelper::map(Category::find()->all(), 'id', 'title');

        $tags = ArrayHelper::map(Tag::find()->all(), 'id', 'title');

        if (Yii::$app->request->isPost) {
            $category = Yii::$app->request->post('category');
            $tags = Yii::$app->request->post('tags');
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                $model->saveCategory($category);
                $model->saveTags($tags);
                return $this->redirect(['/article/article-add-image', 'id' => $model->id]);

            }
        }

        return $this->render('create_article', [
            'model' => $model,
            'categories' => $categories,
            'tags' => $tags,
        ]);
    }

    public function actionArticleAddImage($id) {
        $model = new ImageUpload;

        if (Yii::$app->request->isPost) {

            $article = Article::findOne($id);

            $file = UploadedFile::getInstance($model, 'image');

            if ($article->saveImage($model->uploadFile($file, $article->image))) {
                return $this->redirect(['/article/get', 'id' => $article->id]);
            }
        }

        return $this->render('image', ['model' => $model]);
    }
}

controllers/AuthController.php
<?php
/**
 * Created by PhpStorm.
 * User: yurac
 * Date: 30.01.2019
 * Time: 15:01
 */

namespace app\controllers;


use app\models\forms\LoginForm;
use app\models\forms\SignupForm;
use Yii;
use yii\web\Controller;

class AuthController extends Controller {

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin() {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('/auth/login', [
            'model' => $model,
        ]);
    }

    public function actionSignup() {
        $model = new SignupForm();

        if (Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            if ($model->signup()) {
                return $this->redirect('auth/login');
            }


        }

        return $this->render('signup', ['model' => $model]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\article\Article;
use app\models\category\Category;
use app\models\comment\CommentForm;
use app\models\forms\ImageUpload;
use app\models\tag\Tag;
use app\models\user\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\UploadedFile;

class SiteController extends Controller {
    /**
     * {@inheritdoc}
     */
    public function behaviors() {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex($category_id = null) {

        $data = Article::getAll(4, $category_id);

        $popular = Article::getPopular();

        $categories = Category::getAll();

        $tags = Tag::getAll();

        return $this->render('index', [
            'articles' => $data['articles'],
            'pages' => $data['pages'],
            'popular' => $popular,
            'categories' => $categories,
            'tags' => $tags,
        ]);
    }

}

controllers/UserController.php
<?php
/**
 * Created by PhpStorm.
 * User: yurac
 * Date: 30.01.2019
 * Time: 20:33
 */

namespace app\controllers;


use app\models\article\Article;
use app\models\category\Category;
use app\models\forms\ImageUpload;
use app\models\forms\ProfileForm;
use app\models\tag\Tag;
use app\models\user\User;
use Yii;
use yii\web\Controller;
use yii\web\UploadedFile;

class UserController extends Controller {
    public function actionProfile() {

        $user = User::findOne(Yii::$app->user->id);

        $model = new ProfileForm();

        $model->attributes = $user->attributes;

        return $this->render('profile', ['model' => $model]);
    }

    public function actionSetImage() {
        $model = new ImageUpload;

        if (Yii::$app->request->isPost) {

            $user = User::findOne(Yii::$app->user->id);

            $file = UploadedFile::getInstance($model, 'image');

            if ($user->saveImage($model->uploadFile($file, $user->photo))) {
                return $this->redirect(['profile', 'id' => $user->id]);
            }
        }

        return $this->render('image', ['model' => $model]);
    }

    public function actionArticles($user_id) {
        $data = Article::getAllByUser(4, $user_id);

        $user = User::findOne($user_id);

        $popular = Article::getPopular();

        $categories = Category::getAll();

        $tags = Tag::getAll();

        return $this->render('articles', [
            'articles' => $data['articles'],
            'pages' => $data['pages'],
            'popular' => $popular,
            'categories' => $categories,
            'tags' => $tags,
            'user' => $user,
        ]);
    }

}

views/article/create_article.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\article\Article */
/* @var $form yii\widgets\ActiveForm */
$this->title = 'Написать статью';
?>
<div class="content-wrap">
    <div class="row">
        <div class="article-form">

            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'title')->textInput() ?>

            <?= $form->field($model, 'description')->textInput() ?>

            <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>

            <?= Html::dropDownList('category', null,  $categories, ['class' => 'form-control'])?>

            <?= Html::dropDownList('tags', null,  $tags, ['class' => 'form-control', 'multiple' => true])?>

            <?= $form->field($model, 'date')->textInput() ?>

            <div class="form-group">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>

views/article/image.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Article */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-form">

    <?php $form = ActiveForm::begin(); ?>
    <p>Выберите изображение статьи.</p>

    <?= $form->field($model, 'image')->fileInput(['maxlength' => true]) ?>


    <div class="form-group">
        <?= Html::submitButton('Загрузить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/article/single.php
<!-- Content
   ================================================== -->
<div id="content-wrap">

    <div class="row">

        <div id="main" class="eight columns">

            <article class="entry">

                <header class="entry-header">

                    <h2 class="entry-title">
                        <?= $article->title; ?>
                    </h2>

                    <div class="entry-meta">
                        <ul>
                            <li><?= $article->getDate(); ?></li>
                            <span class="meta-sep">&bull;</span>
                            <li>
                                <a href="#" title="" rel="category tag"><?= $article->category->title; ?></a>
                            </li>
                            <span class="meta-sep">&bull;</span>
                            <?php if (Yii::$app->user->id == $article->user->id): ?>
                                <a href="<?= \yii\helpers\Url::toRoute(['/article/update/', 'id' => $article->id]); ?>">Редактировать</a>
                            <?php else: ?>
                                <li>
                                    <a href="<?= \yii\helpers\Url::toRoute(['/user/articles', 'user_id' => $article->user->id]) ?>"><?= $article->user->name; ?></a>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>

                </header>

                <div class="entry-content-media">
                    <div class="post-thumb">
                        <img src="<?= $article->getImage(); ?>">
                    </div>
                </div>

                <div class="entry-content">
                    <p class="lead">
                        <?= $article->content; ?>
                    </p>
                </div>

                <p class="tags">
                    <span>Tagged in </span>:
                    <?php foreach ($articleTags as $tag): ?>
                        <a href="#"><?= $tag->title; ?></a>
                    <?php endforeach; ?>

                </p>

            </article>

            <!-- Comments
        ================================================== -->
            <div id="comments">
                <?php if (!empty($comments)): ?>
                    <h3><?= count($comments) ?> comments</h3>

                    <!-- commentlist -->
                    <ol class="commentlist">


                        <?php foreach ($comments as $comment): ?>
                            <li class="depth-1">

                                <div class="avatar">
                                    <img width="50" height="50" class="avatar" src="<?= $comment->user->getImage() ?>"
                                         alt="">
                                </div>

                                <div class="comment-content">

                                    <div class="comment-info">
                                        <cite><?= $comment->user->name; ?></cite>

                                        <div class="comment-meta">
                                            <time class="comment-time"
                                                  datetime="<?= $comment->date ?>"><?= $comment->getDate(); ?>
                                            </time>
                                        </div>
                                    </div>

                                    <div class="comment-text">
                                        <p><?= $comment->text; ?></p>
                                    </div>

                                </div>

                            </li>

                        <?php endforeach ?>


                    </ol> <!-- Commentlist End -->

                <?php endif ?>
                <!-- respond -->
                <div class="respond">

                    <?php if (!Yii::$app->user->isGuest): ?>

                        <h3>Оставить комментарий</h3>

                        <!-- form -->
                        <?php $form = \yii\widgets\ActiveForm::begin([
                        'action' => ['site/comment', 'id' => $article->id],
                        'options' => ['class' => 'form-horizontal contantForm', 'role' => 'form']])
                        ?>
                        <fieldset>

                            <div class="message group">
                                <?= $form->field($commentForm, 'comment')->textarea(['class' => 'form-control', 'placeholder' => 'Ваш комментарий'])
                                ?>
                            </div>

                            <button type="submit" class="submit">Отправить</button>

                        </fieldset>
                        <?php \yii\widgets\ActiveForm::end(); ?>
                    <?php endif ?>
                    <!-- Form End -->

                </div> <!-- Respond End -->

            </div>  <!-- Comments End -->


        </div> <!-- main End -->

        <?= $this->render('/partials/sidebar', [
            'popular' => $popular,
            'categories' => $categories,
            'tags' => $tags,
        ]); ?>

    </div> <!-- end row -->

</div> <!-- end content-wrap -->

views/layouts/admin.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Home', 'url' => ['/admin/index']],
            ['label' => 'Статьи', 'url' => ['/admin/article/']],
            ['label' => 'Категории', 'url' => ['/admin/category/']],
            ['label' => 'Теги', 'url' => ['/admin/tag /']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

\app\assets\BlogAssets::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<!-- Header
================================================== -->
<header id="top">

    <div class="row">

        <div class="header-content twelve columns">

            <h1 id="logo-text"><a href="/" title="">Статьи от А до Я.</a></h1>
            <p id="intro">Не придумал как назвать...</p>

        </div>

    </div>

    <nav id="nav-wrap">

        <div class="row">
            <ul id="nav" class="nav">
                <li class="current"><a href="/">Home</a></li>

                <?php if(Yii::$app->user->isGuest):?>
                    <li class="current"><a href="<?= Url::toRoute(['auth/login'])?>">Авторизаваться</a></li>
                    <li class="current"><a href="<?= Url::toRoute(['auth/signup'])?>">Регистрация</a></li>
                <?php else: ?>
                    <li class="current"><a href="<?= Url::toRoute(['user/profile'])?>">Профиль</a></li>
                    <li class="current"><a href="<?= Url::toRoute(['user/articles', 'user_id' => Yii::$app->user->id])?>">Мои статьи</a></li>
                    <li class="current"> <?= Html::beginForm(['/auth/logout'], 'post')
                    . Html::submitButton(
                        'Выйти (' . Yii::$app->user->identity->name . ')',
                        ['class' => 'current']
                    )
                . Html::endForm() ?> </li>
                <?php endif;?>
            </ul> <!-- end #nav -->
        </div>

    </nav> <!-- end #nav-wrap -->

</header> <!-- Header End -->


<?= $content ?>


<!-- Footer
================================================== -->
<footer>

    <div class="row">

        <div class="twelve columns">
            <ul class="social-links">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-github-square"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                <li><a href="#"><i class="fa fa-flickr"></i></a></li>
                <li><a href="#"><i class="fa fa-skype"></i></a></li>
            </ul>
        </div>

        <div class="six columns info">

            <p>This is Photoshop's version  of Lorem Ipsum. Proin gravida nibh vel velit auctor aliquet.
                Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem
                nibh id elit.
            </p>

            <p>Lorem ipsum Sed nulla deserunt voluptate elit occaecat culpa cupidatat sit irure sint
                sint incididunt cupidatat esse in Ut sed commodo tempor consequat culpa fugiat incididunt.</p>

        </div>

        <div class="two columns">
            <h3 class="social">Navigate</h3>

            <ul class="navigate group">
                <li><a href="#">Home</a></li>
            </ul>
        </div>

    </div> <!-- End row -->

    <div id="go-top"><a class="smoothscroll" title="Back to Top" href="#top"><i class="fa fa-chevron-up"></i></a></div>

</footer> <!-- End Footer-->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/partials/sidebar.php
<div id="sidebar" class="four columns">

    <div class="widget widget_categories group">
        <h3>Categories.</h3>
        <ul>
            <?php foreach ($categories as $category): ?>
                <li><a href="<?= \yii\helpers\Url::toRoute(['/site/index', 'category_id' => $category->id])?>" title=""><?= $category->title; ?></a> (<?= $category->getArticlesCount(); ?>
                    )
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <div class="widget widget_text group">
        <h3>Widget Text.</h3>

        <p>Lorem ipsum Ullamco commodo laboris sit dolore commodo aliquip incididunt fugiat esse dolor aute
            fugiat minim eiusmod do velit labore fugiat officia ad sit culpa labore in consectetur sint cillum
            sint consectetur voluptate adipisicing Duis irure magna ut sit amet reprehenderit.</p>

    </div>

    <div class="widget widget_tags">
        <h3>Post Tags.</h3>

        <div class="tagcloud group">
            <?php foreach ($tags as $tag): ?>
                <a href="#"><?= $tag->title; ?></a>
            <?php endforeach ?>

        </div>

    </div>

    <div class="widget widget_popular">
        <h3>Popular Post.</h3>

        <ul class="link-list">
            <?php foreach ($popular as $article): ?>
                <li><a href="<?= \yii\helpers\Url::toRoute(['/site/single', 'id' => $article->id])?>"><?= $article->title; ?></a></li>
            <?php endforeach; ?>

        </ul>

    </div>

</div> <!-- end sidebar -->

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\widgets\LinkPager;

$this->title = 'Статьи от А до Я';
?>
<!-- Content
================================================== -->
<div id="content-wrap">

    <div class="row">


        <div id="main" class="eight columns">

            <?php foreach ($articles as $article): ?>

                <article class="entry">

                    <header class="entry-header">

                        <h2 class="entry-title">
                            <a href="<?= \yii\helpers\Url::toRoute(['/article/get/', 'id' => $article->id]); ?>"
                               title=""> <?= $article->title; ?> </a>
                        </h2>

                        <div class="entry-meta">
                            <ul>
                                <li><?= $article->getDate(); ?></li>
                                <span class="meta-sep">&bull;</span>
                                <li>
                                    <a href="<?= \yii\helpers\Url::toRoute(['/site/index', 'category_id' => $article->category->id]) ?>"
                                       title="" rel="category tag"><?= $article->category->title; ?></a></li>
                                <span class="meta-sep">&bull;</span>
                                <li><a href="<?= \yii\helpers\Url::toRoute(['/user/articles', 'user_id' => $article->user->id]) ?>"><?= $article->user->name; ?></a></li>
                            </ul>
                        </div>

                    </header>

                    <div class="entry-content">
                        <p><?= $article->description; ?></p>
                    </div>

                </article>
            <?php endforeach; ?>

            <?php if (!Yii::$app->user->isGuest): ?>
                <a href="<?= \yii\helpers\Url::toRoute(['/article/add-article/']); ?>">
                    <button class="btn btn-default">Написать статью</button>
                </a>
            <?php endif ?>

            <?php echo LinkPager::widget([
                'pagination' => $pages,
            ]); ?>
        </div> <!-- end main -->

        <?= $this->render('/partials/sidebar', [
            'popular' => $popular,
            'categories' => $categories,
            'tags' => $tags,
        ]); ?>

    </div> <!-- end row -->

</div> <!-- end content-wrap -->

views/user/articles.php
<?php

/* @var $this yii\web\View */

use yii\widgets\LinkPager;

$this->title = 'Статьи ' . $user->name;
?>
<!-- Content
================================================== -->
<div id="content-wrap" style="padding-top: 0;">

    <div class="row">

        <div class="header-content twelve columns">

            <ol class="commentlist" style="margin-top: 0">
                <li class="depth-1">

                    <div class="avatar">
                        <img width="150" height="150" class="avatar" src="<?= $user->getImage()?>" alt="">
                    </div>

                    <div class="comment-content">

                        <div class="comment-info">
                            <cite><?= $user->name; ?></cite>
                        </div>

                        <div class="comment-text">
                            <p><?= $user->description; ?></p>
                            <p><?= $user->email; ?></p>
                        </div>

                    </div>

                </li>
            </ol>

        </div>

        <div id="main" class="eight columns">

            <?php foreach ($articles as $article): ?>

                <article class="entry">

                    <header class="entry-header">

                        <h2 class="entry-title">
                            <a href="<?= \yii\helpers\Url::toRoute(['/site/single/', 'id' => $article->id]); ?>"
                               title=""> <?= $article->title; ?> </a>
                        </h2>

                        <div class="entry-meta">
                            <ul>
                                <li><?= $article->getDate(); ?></li>
                                <span class="meta-sep">&bull;</span>
                                <li>
                                    <a href="<?= \yii\helpers\Url::toRoute(['/site/index', 'category_id' => $article->category->id]) ?>"
                                       title="" rel="category tag"><?= $article->category->title; ?></a></li>
                                <span class="meta-sep">&bull;</span>
                                <?php if (Yii::$app->user->id == $article->user->id): ?>
                                    <a href="<?= \yii\helpers\Url::toRoute(['/site/update-article/', 'id' => $article->id]); ?>">Редактировать</a>
                                <?php else: ?>
                                    <li><?= $article->user->name; ?></li>
                                <?php endif; ?>


                            </ul>
                        </div>

                    </header>

                    <div class="entry-content">
                        <p><?= $article->description; ?></p>
                    </div>

                </article>
            <?php endforeach; ?>

            <?php if (!Yii::$app->user->isGuest): ?>
                <a href="<?= \yii\helpers\Url::toRoute(['/site/add-article/']); ?>">
                    <button class="btn btn-default">Написать статью</button>
                </a>
            <?php endif ?>

            <?php echo LinkPager::widget([
                'pagination' => $pages,
            ]); ?>
        </div> <!-- end main -->

        <?= $this->render('/partials/sidebar', [
            'popular' => $popular,
            'categories' => $categories,
            'tags' => $tags,
        ]); ?>

    </div> <!-- end row -->

</div> <!-- end content-wrap -->

views/user/image.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Article */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="content-wrap">
    <div class="row">
        <div class="article-form">

            <?php $form = ActiveForm::begin(); ?>

            <?= $form->field($model, 'image')->fileInput(['maxlength' => true]) ?>


            <div class="form-group">
                <?= Html::submitButton('Загрузить', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
</div>